version: '3.8'

services:
  whisper-api:
    build: .
    # 다음 설정은 network_mode: host를 사용할 때는 무시됩니다
    ports:
       - "11435:5000"
    volumes:
      - ./uploads:/app/uploads
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
